### ISSUE TITLE
Keys problem

### ISSUE THREAD

**Issue by nafing** [electrotelco/Fivem-ESX#2]
Maybe someone knows how to give keys after buying a vehicle and after taking the vehicle out of the garage on the example of netr_garages

**Comment by userMacieG** [comment]
> Maybe someone knows how to give keys after buying a vehicle and after taking the vehicle out of the garage on the example of netr_garages

Hi, can you give some contact to you? I'm looking for your `nafing_police` script.

**Comment by nafing** [comment]
> > Maybe someone knows how to give keys after buying a vehicle and after taking the vehicle out of the garage on the example of netr_garages
> 
> Hi, can you give some contact to you? I'm looking for your `nafing_police` script.

✪ dydolek#7227 DC

**Comment by electrotelco** [comment]
> Hi, can you give some contact to you? I'm looking for your `nafing_police` script.

what do you mean by "nafing"? I have no more published scripts

**Comment by iSentrie** [comment]
> > Hi, can you give some contact to you? I'm looking for your `nafing_police` script.
> 
> what do you mean by "nafing"? I have no more published scripts

"nafing" is from krzaqn.
